package Entity;
// Generated Oct 19, 2018 5:20:48 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Phongban generated by hbm2java
 */
@Entity
@Table(name = "phongban", catalog = "quanlythanhtichabc")
public class Phongban implements java.io.Serializable {

	private String maphong;
	private String tenphong;
	private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(0);
	private Set<Thanhtichkyluat> thanhtichkyluats = new HashSet<Thanhtichkyluat>(0);

	public Phongban() {
	}

	public Phongban(String maphong, String tenphong) {
		this.maphong = maphong;
		this.tenphong = tenphong;
	}

	public Phongban(String maphong, String tenphong, Set<Nhanvien> nhanviens, Set<Thanhtichkyluat> thanhtichkyluats) {
		this.maphong = maphong;
		this.tenphong = tenphong;
		this.nhanviens = nhanviens;
		this.thanhtichkyluats = thanhtichkyluats;
	}

	@Id

	@Column(name = "maphong", unique = true, nullable = false, length = 2)
	public String getMaphong() {
		return this.maphong;
	}

	public void setMaphong(String maphong) {
		this.maphong = maphong;
	}

	@Column(name = "tenphong", nullable = false, length = 100)
	public String getTenphong() {
		return this.tenphong;
	}

	public void setTenphong(String tenphong) {
		this.tenphong = tenphong;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phongban")
	public Set<Nhanvien> getNhanviens() {
		return this.nhanviens;
	}

	public void setNhanviens(Set<Nhanvien> nhanviens) {
		this.nhanviens = nhanviens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phongban")
	public Set<Thanhtichkyluat> getThanhtichkyluats() {
		return this.thanhtichkyluats;
	}

	public void setThanhtichkyluats(Set<Thanhtichkyluat> thanhtichkyluats) {
		this.thanhtichkyluats = thanhtichkyluats;
	}

}
